apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookalbum_nak
  labels:
    app: bookalbum_nak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookalbum_nak
  template:
    metadata:
      labels:
        app: bookalbum_nak
    spec:
      containers:
      - name: bookalbum_nak
        image: nibha1611/bookmoviealbum:latest
        ports:
        - containerPort: 80
