apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookalbumnak
  labels:
    app: bookalbumnak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookalbumnak
  template:
    metadata:
      labels:
        app: bookalbumnak
    spec:
      containers:
      - name: bookalbumnak
        image: nibha1611/bookmoviealbum:latest
        ports:
        - containerPort: 80
