apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookalbumnak
  name: bookalbumnak
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bookalbumnak

