apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookalbum_nak
  name: bookalbum_nak
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bookalbum_nak

